'use client'
import Button from '@mui/material/Button'
import axios from 'axios'
import Head from 'next/head'
import { useEffect } from 'react'

export default function Home() {
  const fetchData = async () => {
    await axios.get('http://localhost:3001/api/users').then(res => {
      console.log('data')
    })
  }

  useEffect(() => {
    fetchData()
  }, [])

  return (
    <>
      <Head>
        <title>Lập trình thật dễ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Button variant='contained'>Hello world dangnhsss</Button>
    </>
  )
}
